name: Static Next Build
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Yarn install
        run: yarn

      - name: Next build
        run: npx next build

      - name: Notify failure
        if: ${{ failure() }}
        run: echo build failed !!!!

      - name: Take a lap to see what is real
        run: ls out

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy out/ --project-name xc40-phev
